# Generated by Django 3.2 on 2023-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='book_issue_date',
            field=models.IntegerField(),
        ),
    ]
