# Generated by Django 3.2 on 2023-05-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_room_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='book_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='book_issue_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
