# Generated by Django 3.2 on 2023-05-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230502_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='book_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
