# Generated by Django 3.2 on 2023-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_room_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='book_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
