# Generated by Django 3.2 on 2023-05-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_room_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='book_quantity',
        ),
    ]
