# Generated by Django 4.2 on 2023-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_room_options_rename_book_author_room_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='book_issue_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
