# Generated by Django 4.2 on 2023-05-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_room_book_category_room_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='book_issue_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated',
        ),
    ]
