# Generated by Django 4.2.1 on 2023-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_name_room_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='book_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
