# Generated by Django 4.2.1 on 2023-05-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_category_description_room_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_link',
            field=models.CharField(default='https://twinklelearning.in/uploads/noimage.jpg', max_length=200, null=True),
        ),
    ]
