# Generated by Django 4.2.1 on 2023-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_librarian_requested_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='requested_books',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
