# Generated by Django 4.2.1 on 2023-05-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_librarian_requested_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='requested_books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
