# Generated by Django 4.2.1 on 2023-05-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_student_requested_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=200)),
                ('requester_id', models.IntegerField()),
                ('requester_name', models.CharField(max_length=200)),
                ('issuer_id', models.IntegerField(null=True)),
                ('is_returned', models.BooleanField(default=False)),
            ],
        ),
    ]
