# Generated by Django 4.2.1 on 2023-05-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='copies_available',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
