# Generated by Django 4.2.1 on 2023-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_requests_copies_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='issued',
            field=models.BooleanField(default=False),
        ),
    ]
