# Generated by Django 4.2.1 on 2023-05-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_requests_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='issued_books',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='held_books',
            field=models.TextField(blank=True, null=True),
        ),
    ]
