# Generated by Django 4.2.1 on 2023-05-23 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_requests_id_requests_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
