# Generated by Django 4.2.1 on 2023-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_librarian_requested_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='issued',
            new_name='is_issued',
        ),
        migrations.AddField(
            model_name='requests',
            name='issue_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='issuer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='return_time',
            field=models.DateTimeField(null=True),
        ),
    ]
