# Generated by Django 4.2.1 on 2023-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_issued_requests_is_issued_requests_issue_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='issue_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='return_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
